const sampleListings = [
  {
    title: "Luxury Beach Villa",
    description: "Beautiful villa near the beach with private pool.",
    image: {
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
      filename: "listingimage",
    },
    price: 3500,
    location: "Goa",
    country: "India",
  },
  {
    title: "Mountain View Cabin",
    description: "Cozy cabin with mountain views.",
    image: {
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
      filename: "listingimage",
    },
    price: 2000,
    location: "Manali",
    country: "India",
  },
  {
    title: "Lake Side Cottage",
    description: "Relaxing stay near lake.",
    image: {
      url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
      filename: "listingimage",
    },
    price: 1800,
    location: "Nainital",
    country: "India",
  },
  {
    title: "Royal Heritage Haveli",
    description: "Royal stay experience.",
    image: {
      url: "https://images.unsplash.com/photo-1564501049412-61c2a3083791",
      filename: "listingimage",
    },
    price: 4000,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Backwater Villa",
    description: "Peaceful Kerala stay.",
    image: {
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
      filename: "listingimage",
    },
    price: 3200,
    location: "Alleppey",
    country: "India",
  },
  {
    title: "Modern Apartment",
    description: "City center apartment.",
    image: {
      url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
      filename: "listingimage",
    },
    price: 2500,
    location: "Mumbai",
    country: "India",
  },
  {
    title: "Hilltop Retreat",
    description: "Stay in tea gardens.",
    image: {
      url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
      filename: "listingimage",
    },
    price: 2200,
    location: "Munnar",
    country: "India",
  },
  {
    title: "Desert Camp",
    description: "Luxury desert stay.",
    image: {
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
      filename: "listingimage",
    },
    price: 2700,
    location: "Jaisalmer",
    country: "India",
  },
  {
    title: "Beach Hut",
    description: "Simple beach stay.",
    image: {
      url: "https://images.unsplash.com/photo-1493558103817-58b2924bce98",
      filename: "listingimage",
    },
    price: 1200,
    location: "Gokarna",
    country: "India",
  },
  {
    title: "Luxury Penthouse",
    description: "Top floor luxury stay.",
    image: {
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
      filename: "listingimage",
    },
    price: 5000,
    location: "Delhi",
    country: "India",
  },
  {
    title: "Forest Treehouse",
    description: "Stay in forest treehouse.",
    image: {
      url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e",
      filename: "listingimage",
    },
    price: 2100,
    location: "Wayanad",
    country: "India",
  },
  {
    title: "Snow Chalet",
    description: "Snow mountain stay.",
    image: {
      url: "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66",
      filename: "listingimage",
    },
    price: 2600,
    location: "Shimla",
    country: "India",
  },
  {
    title: "Riverfront Stay",
    description: "Stay beside river.",
    image: {
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
      filename: "listingimage",
    },
    price: 1900,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Tea Estate Bungalow",
    description: "Tea garden stay.",
    image: {
      url: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429",
      filename: "listingimage",
    },
    price: 2800,
    location: "Darjeeling",
    country: "India",
  },
  {
    title: "Cliffside Villa",
    description: "Cliff view villa.",
    image: {
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
      filename: "listingimage",
    },
    price: 3600,
    location: "Varkala",
    country: "India",
  },
  {
    title: "Island Resort",
    description: "Island vibes stay.",
    image: {
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
      filename: "listingimage",
    },
    price: 4200,
    location: "Andaman",
    country: "India",
  },
  {
    title: "Fort Stay",
    description: "Historic fort stay.",
    image: {
      url: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da",
      filename: "listingimage",
    },
    price: 4500,
    location: "Jodhpur",
    country: "India",
  },
  {
    title: "Farm Stay",
    description: "Organic farm experience.",
    image: {
      url: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6",
      filename: "listingimage",
    },
    price: 1700,
    location: "Pune",
    country: "India",
  },
  {
    title: "Studio Flat",
    description: "Compact city flat.",
    image: {
      url: "https://images.unsplash.com/photo-1493666438817-866a91353ca9",
      filename: "listingimage",
    },
    price: 1400,
    location: "Bangalore",
    country: "India",
  },
  {
    title: "Houseboat",
    description: "Stay on water.",
    image: {
      url: "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
      filename: "listingimage",
    },
    price: 3800,
    location: "Kerala",
    country: "India",
  },
  {
    title: "Hill Cottage",
    description: "Cozy hill stay.",
    image: {
      url: "https://images.unsplash.com/photo-1505691723518-36a5ac3b2d4d",
      filename: "listingimage",
    },
    price: 2000,
    location: "Mussoorie",
    country: "India",
  },
  {
    title: "Luxury Resort",
    description: "5-star experience.",
    image: {
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
      filename: "listingimage",
    },
    price: 5500,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Village Homestay",
    description: "Rural experience.",
    image: {
      url: "https://images.unsplash.com/photo-1523217582562-09d0def993a6",
      filename: "listingimage",
    },
    price: 1100,
    location: "Punjab",
    country: "India",
  },
  {
    title: "Jungle Lodge",
    description: "Stay inside jungle.",
    image: {
      url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
      filename: "listingimage",
    },
    price: 3300,
    location: "Jim Corbett",
    country: "India",
  },
  {
    title: "Beach Resort",
    description: "Sea facing stay.",
    image: {
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
      filename: "listingimage",
    },
    price: 2900,
    location: "Pondicherry",
    country: "India",
  },
  {
    title: "Glass House",
    description: "Modern glass house.",
    image: {
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
      filename: "listingimage",
    },
    price: 4100,
    location: "Hyderabad",
    country: "India",
  },
  {
    title: "Hill Apartment",
    description: "Scenic hill view.",
    image: {
      url: "https://images.unsplash.com/photo-1494526585095-c41746248156",
      filename: "listingimage",
    },
    price: 2300,
    location: "Dehradun",
    country: "India",
  },
  {
    title: "Temple Stay",
    description: "Near temple location.",
    image: {
      url: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429",
      filename: "listingimage",
    },
    price: 1600,
    location: "Varanasi",
    country: "India",
  },
  {
    title: "Palace Stay",
    description: "Royal palace living.",
    image: {
      url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
      filename: "listingimage",
    },
    price: 6000,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Budget Hostel",
    description: "Affordable stay.",
    image: {
      url: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5",
      filename: "listingimage",
    },
    price: 800,
    location: "Delhi",
    country: "India",
  },
];

module.exports = { data: sampleListings };